name: Build and Release APK
on: push
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - uses: subosito/flutter-action@v1
          with:
            channel: 'stable'

        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release
          working-directory: ./

        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy hosting:vego-9f996
          env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
            PROJECT_PATH: ./